### ISSUE TITLE
BCO Accession and Name sorting not working

### ISSUE THREAD

**Issue by kmartinez834** [biocompute-objects/portal#204] opened 2022-07-12 19:37 UTC
# **Describe the bug**
On the Biocompute Object DB page, the BCO accessions are out of order.  When I click on the Accession or Name header, an arrow appears (indicating that the rows should be sorted) but the order does not change.

# **To Reproduce**
1. Go to https://test.portal.biochemistry.gwu.edu/objects
2. Use prefix search to generate list of GLY BCOs
3. Click on "BCO Accession" or "Name" header

# **Expected behavior**
Rows should be sorted in ascending or descending order, depending on arrow direction.  Presumably, GLY_000001 would appear first if I click on the BCO Accession header.

# **Screenshots**

![image](https://user-images.githubusercontent.com/90285371/178579348-65662d61-f975-4b22-b14c-3a81e6f75bda.png)

# **Desktop (please complete the following information):**

 - OS: Windows10
 - Browser  Chrome

# **Additional context**

***[ADD ANY ADDITONAL INFORMATION YOU FEEL WASN'T INCLUDED ABOVE. PUT N/A IF THERE IS NONE]***

**Comment by HadleyKing** [comment] 2022-07-16 14:41
The table headers and tables in the page have not been updated in synch with the functions that generate the sort ability.

**Comment by HadleyKing** [comment] 2022-07-16 14:46
Thanks for reporting @kmartinez834. This is a duplicate of #168 and so will get closed.

**Closed by HadleyKing** 2022-07-16 14:46 UTC
Labels: bug, duplicate
