### ISSUE TITLE
Can't see BCOs

### ISSUE THREAD

**Issue by kee007ney** [biocompute-objects/portal#141] opened 2022-04-18 18:59 UTC
# **Describe the bug**
*A clear and concise description of what the bug is.*

Objects are not listing.

# **To Reproduce**
*Steps to reproduce the behavior:*

Click on BioCompute Objects in top menu

# **Expected behavior**
*A clear and concise description of what you expected to happen.*

A listing of BCOs

# **Screenshots**
![Err08](https://user-images.githubusercontent.com/12193741/163860677-88e0c4e5-7c7c-4b8a-90d7-43dc65ad43a7.png)

# **Desktop (please complete the following information):**

 - OS:  Windows10
 -  - Browser  Tried in Brave, Edge, Firefox, Chrome...

**Comment by kee007ney** [comment] 2022-04-19 14:17
This is not a bug, just needs documentation.

**Comment by HadleyKing** [comment] 2022-04-21 15:17
Duplicate of #134

**Closed by HadleyKing** 2022-04-21 15:17 UTC
Labels: duplicate
